version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock